
const ACTION_CONTAINER = {
	SHOW_DATA:'SHOW_DATA',
	CHANGE_DATA:'CHANGE_DATA',
	LOGIN_SUCCESS:'LOGIN_SUCCESS',
	LOGIN_FAILED:'LOGIN_FAILED',
	APIURL:'http://172.24.5.36:3001',
	LISTDATA:'LISTDATA',
	FAILED:'Something went wrong please try again.',
	SHOW_LOADER:'SHOW_LOADER',
	HIDE_LOADER:'HIDE_LOADER',
	API_ERROR:'API_ERROR',

	VENDOR_ITEMSADDED:'VENDOR_ITEMSADDED',
	USERDETAILSTORE:'USERDETAILSTORE',
	FORGOT_PASSWORD_MESSAGE:'FORGOT_PASSWORD_MESSAGE',
	PRODUCT_DETAIL:'PRODUCT_DETAIL',
	LOGOUT:'LOGOUT',
	ADDTOCART:'ADDTOCART',
	PAYMENTRESULT:'PAYMENTRESULT',
	PAYMENTREFRESHRESULT:'PAYMENTREFRESHRESULT',
	VENDORORDERLIST:'VENDORORDERLIST',
	CUSTOMERORDERLIST:'CUSTOMERORDERLIST',
	ORDERCONFIRM:'ORDERCONFIRM',
	CUSTOMERORDERLISTREFRESH:'CUSTOMERORDERLISTREFRESH',
	STOPREFRESH:'STOPREFRESH',
	ALLCARDS:'ALLCARDS',
	ADDNEWCARD:'ADDNEWCARD',
	USERTYPE:'USERTYPE',
	CURRENTSELECTEDCARD:'CURRENTSELECTEDCARD',
	DEVICETOKEN:'DEVICETOKEN',
	VENDORITEMLIST:'VENDORITEMLIST',
	USERPROFILEUPDATE:'USERPROFILEUPDATE',

	REFRESH_STORE: 'REFRESH_STORE',
	REFRESH_APITAG:'REFRESH_APITAG',
	LOGIN_USER:'LOGIN_USER',
	SIGNUP_USER:'SIGNUP_USER',
	CATEGORIES:'CATEGORIES',

}

export default ACTION_CONTAINER
